package org.omg.PortableInterceptor;


/**
* org/omg/PortableInterceptor/INACTIVE.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/cygwin64/tmp/build/source/java-1.8.0-openjdk/tmp/jdk8u/corba/src/share/classes/org/omg/PortableInterceptor/Interceptors.idl
* Monday, January 11, 2021 12:19:00 PM PST
*/

public interface INACTIVE
{

  /** Object adapter state that causes all requests to be discarded.
   * This state indicates that the adapter is shutting down.
   */
  public static final short value = (short)(3);
}
