package org.omg.IOP;


/**
* org/omg/IOP/TransactionService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/cygwin64/tmp/build/source/java-1.8.0-openjdk/tmp/jdk8u/corba/src/share/classes/org/omg/PortableInterceptor/IOP.idl
* Monday, January 11, 2021 12:18:59 PM PST
*/

public interface TransactionService
{

  /**
     * Identifies a CDR encapsulation of the 
     * <code>CosTSInteroperation.PropogationContext</code> defined in 
     * <i>CORBAservices: Common Object Services Specifications.</i>
     */
  public static final int value = (int)(0L);
}
